# Configuration for dataset format conversion using Draccus
mode: "image_to_npy"  # Options: "coco_to_yolo", "image_to_npy"

coco_config:
  json_path: "/home/duykhongcay/hailo_ws/chess_pieces_detection/datasets/annotations.json"
  images_dir: "/home/duykhongcay/hailo_ws/chess_pieces_detection/datasets/images"
  output_dir: "/home/duykhongcay/hailo_ws/chess_pieces_detection/datasets/chessred"
  max_images: 2500
  # seed: 42

image_config:
  images_dir: /home/duykhongcay/hailo_ws/chess_pieces_detection/datasets/rbflow_chesspieces_dataset/train/images
  output_npy: "/home/duykhongcay/hailo_ws/chess_pieces_detection/datasets/rbflow_chesspieces_dataset/calib_dataset.npy"
  imgsz: 640
  dtype: "float32"
  num_samples: 16
  seed: 42

