# Hailo Export Configuration for Joined Model (YOLO11n-det + YOLOv8n-seg)

model_name: "auto_join_inputs"
calib_dir: "/home/duykhongcay/hailo_ws/chess_pieces_detection/datasets/rbflow_chesspieces_dataset/train/images"
output_dir: "/home/duykhongcay/hailo_ws/chess_pieces_detection/runs/hailo_joined_model"
hw_arch: "hailo8"
imgsz: 640
calib_count: 1024
device: "0"

end_node_names: null

model_script:
  - "normalization1 = normalization([0.0, 0.0, 0.0], [255.0, 255.0, 255.0])"
  - "model_optimization_flavor(optimization_level=2, batch_size=1)"
  - "nms_postprocess(config_path='/home/duykhongcay/hailo_ws/chess_pieces_detection/runs/hailo_joined_model/yolo11n_nms_config.json', meta_arch=yolov8)"
  - "quantization_param(yolov8n-seg/output_layer2, precision_mode=a16_w16)"
  - "quantization_param(yolov8n-seg/output_layer6, precision_mode=a16_w16)"
  - "allocator_param(optimization_level=1, timeout=300)"

stage: "compile"