# Inference configuration for chess piece detection, perspective transformation, and 2x2 visualization using Draccus
source: /home/duykhongcay/hailo_ws/chess_pieces_detection/datasets/imx219_captures/right/right_0000.jpg
# model: /home/duykhongcay/hailo_ws/chess_pieces_detection/runs/chess_detection_yolo11n-2/yolo11n.hef
model: /home/duykhongcay/hailo_ws/chess_pieces_detection/runs/chess_detection_yolo11n-3/weights/best.pt
output_dir: /home/duykhongcay/hailo_ws/chess_pieces_detection/runs/predict
conf: 0.25
iou: 0.65
imgsz: 640
device: 'cpu'
object_detect_only: false
board_segment_only: false
# Board Segmentor Configuration
seg_model: /home/duykhongcay/hailo_ws/chess_pieces_detection/runs/chessboard_yolo8n-seg/hailo_model/yolov8n-seg.hef
