# Inference configuration for chess piece detection, perspective transformation, and 2x2 visualization using Draccus
source: ../ros2_ws/debug_left.jpg
# model: AI_Chess/runs/detect/train4/weights/best.pt
model: chess_pieces_detection/best.pt
output_dir: chess_pieces_detection/runs/predict
conf: 0.3
iou: 0.6
imgsz: 1024
device: 'cpu'
# Board Segmentor Configuration
seg_source_type: "local"
seg_model: chess_pieces_detection/pretrained_models/chess_board_yolo11.pt
# seg_model: "chessboard-segmentation/1"
# roboflow_api_key: "qlW2c4LOJkr0NkVrdkYH"
# roboflow_api_url: "https://serverless.roboflow.com"