# Inference configuration for chess piece detection, perspective transformation, and 2x2 visualization using Draccus
source: chess_pieces_detection/datasets/images/0/G000_IMG005.jpg
# model: AI_Chess/runs/detect/train4/weights/best.pt
model: AI_Chess/runs/detect/train2/weights/best.pt
output_dir: chess_pieces_detection/runs/predict
conf: 0.2
iou: 0.7
imgsz: 416
device: '0'
# Board Segmentor Configuration
seg_source_type: "local"
seg_model: AI_Chess/board_seg/exp13/weights/best.pt
# seg_model: "chessboard-segmentation/1"
# roboflow_api_key: "qlW2c4LOJkr0NkVrdkYH"
# roboflow_api_url: "https://serverless.roboflow.com"