# Roboflow private API key
api_key: BBa42pbZMPubiGI6d9XI
# Roboflow workspace ID
workspace: duykhongcay
# Roboflow project ID
project: chessboard-segmentation-1tynm
# Model name identifier (used for versionless deploy; only alphanumeric and dashes allowed)
model_name: realchessboard-yolov8n-seg
model_type: yolov8n
model_path: /home/duykhongcay/hailo_ws/chess_pieces_detection/runs/chessboard_yolo8n-seg/weights
weights_filename: best.pt
# Project version ID (set null/empty for versionless deploy, or specify int version e.g. 4)
version: 2